# Generated by Django 4.2.7 on 2025-10-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('DATACENTER', 'Datacenter'), ('MOBILE', 'Mobile'), ('ISP', 'ISP')], max_length=20)),
                ('ip_address', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('success_rate', models.FloatField(default=100.0)),
            ],
            options={
                'verbose_name': 'Proxy Pool',
                'verbose_name_plural': 'Proxy Pools',
                'db_table': 'proxy_pools',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('hashed_password', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_id', models.IntegerField()),
                ('data_used_mb', models.FloatField(default=0.0)),
                ('request_count', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='backoffice.user')),
            ],
            options={
                'db_table': 'usage_logs',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('data_limit_gb', models.FloatField()),
                ('data_used_gb', models.FloatField(default=0.0)),
                ('proxy_requests_limit', models.IntegerField(default=1000)),
                ('proxy_requests_used', models.IntegerField(default=0)),
                ('concurrent_connections', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='backoffice.user')),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': True,
            },
        ),
    ]
