# Generated by Django 4.2.7 on 2025-10-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='proxy_requests_limit',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='proxy_requests_used',
        ),
        migrations.AddField(
            model_name='proxypool',
            name='current_users',
            field=models.IntegerField(default=0, help_text='Current number of users assigned to this proxy'),
        ),
        migrations.AddField(
            model_name='proxypool',
            name='max_users',
            field=models.IntegerField(default=10, help_text='Max users that can use this proxy. Set to 1 for dedicated.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='allocated_proxies_count',
            field=models.IntegerField(default=0, help_text='How many proxies currently allocated'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='allocated_proxies_limit',
            field=models.IntegerField(default=10, help_text='How many proxies user can allocate'),
        ),
        migrations.CreateModel(
            name='UserAllocatedProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_port', models.IntegerField(help_text="Port on Gateway server for this user's proxy")),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('proxy_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='backoffice.proxypool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_proxies', to='backoffice.user')),
            ],
            options={
                'db_table': 'user_allocated_proxies',
                'managed': True,
                'indexes': [models.Index(fields=['user', 'gateway_port'], name='user_alloca_user_id_1595cd_idx'), models.Index(fields=['gateway_port'], name='user_alloca_gateway_c49891_idx')],
                'unique_together': {('user', 'gateway_port')},
            },
        ),
    ]
