# Generated by Django 4.2.7 on 2025-10-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_remove_subscription_proxy_requests_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxypool',
            name='proxy_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('datacenter', 'Datacenter'), ('mobile', 'Mobile'), ('isp', 'ISP')], max_length=20),
        ),
    ]
