# Generated by Django 4.2.7 on 2025-10-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_alter_proxypool_proxy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxypool',
            name='password',
            field=models.CharField(default=1, max_length=66),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proxypool',
            name='scheme',
            field=models.PositiveSmallIntegerField(choices=[(0, 'socks5'), (1, 'http')], default=0),
        ),
        migrations.AddField(
            model_name='proxypool',
            name='username',
            field=models.CharField(default=1, max_length=89),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proxypool',
            name='proxy_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'RESIDENTIAL'), ('DATACENTER', 'DATACENTER'), ('MOBILE', 'MOBILE'), ('ISP', 'ISP')], max_length=20),
        ),
    ]
